name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, macos-14, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    defaults:
      run:
          working-directory: ./rusty-connect-tauri
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libxcb-xfixes0-dev libxcb-shape0-dev
          version: 1.0
          
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: 'v0.19.0'
      - name: Read and Replace Cargo.toml
        run: python3 ../.github/update_cargo_toml.py

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './rusty-connect-tauri -> target'
          
      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'Rusty Connect v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: true
          includeDebug: true
